State.init({ count: 0 });

const increment = () => State.update({ count: state.count + 1 });

return (
  <div style={{
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    padding: 16,
    fontFamily: "Inter, system-ui, sans-serif",
    maxWidth: 420,
    background: "#fff"
  }}>
    <h3 style={{ marginTop: 0, marginBottom: 8 }}>demo-minimal</h3>
    <p style={{ marginTop: 0, color: "#6b7280" }}>Generated by mcp-near-bos-component-builder</p>

    <button
      onClick={increment}
      style={{
        marginTop: 8,
        border: 0,
        borderRadius: 10,
        padding: "10px 14px",
        cursor: "pointer",
        background: "#111827",
        color: "white"
      }}
    >
      Count: {state.count}
    </button>
  </div>
);
