export type TemplateName = "minimal" | "token-swap-widget" | "portfolio-card";

export interface TemplateRenderContext {
  componentName: string;
  description?: string;
}

export interface TemplateDefinition {
  name: TemplateName;
  title: string;
  description: string;
  tags: string[];
  render: (ctx: TemplateRenderContext) => string;
}

const templates: Record<TemplateName, TemplateDefinition> = {
  minimal: {
    name: "minimal",
    title: "Minimal Counter Card",
    description: "Small stateful component with a simple action and clean card layout.",
    tags: ["starter", "ui", "state"],
    render: ({ componentName, description }) => `State.init({ count: 0 });

const increment = () => State.update({ count: state.count + 1 });

return (
  <div style={{
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    padding: 16,
    fontFamily: "Inter, system-ui, sans-serif",
    maxWidth: 420,
    background: "#fff"
  }}>
    <h3 style={{ marginTop: 0, marginBottom: 8 }}>${componentName}</h3>
    <p style={{ marginTop: 0, color: "#6b7280" }}>${description ?? "Generated by mcp-near-bos-component-builder"}</p>

    <button
      onClick={increment}
      style={{
        marginTop: 8,
        border: 0,
        borderRadius: 10,
        padding: "10px 14px",
        cursor: "pointer",
        background: "#111827",
        color: "white"
      }}
    >
      Count: {state.count}
    </button>
  </div>
);
`
  },
  "token-swap-widget": {
    name: "token-swap-widget",
    title: "Token Swap Widget",
    description: "Swap UI scaffold with placeholders for routing and quote hooks.",
    tags: ["defi", "swap", "form"],
    render: ({ componentName, description }) => `State.init({ fromToken: "NEAR", toToken: "USDC", amount: "1" });

const onSwap = () => {
  // TODO: connect router call / transaction flow
  console.log("swap", state.fromToken, state.toToken, state.amount);
};

return (
  <div style={{
    border: "1px solid #d1d5db",
    borderRadius: 12,
    padding: 16,
    maxWidth: 460,
    fontFamily: "Inter, system-ui, sans-serif",
    background: "#fff"
  }}>
    <h3 style={{ marginTop: 0, marginBottom: 8 }}>${componentName}</h3>
    <p style={{ marginTop: 0, color: "#6b7280" }}>${description ?? "Swap widget scaffold for BOS"}</p>

    <div style={{ display: "grid", gap: 10 }}>
      <input
        value={state.amount}
        onChange={(e) => State.update({ amount: e.target.value })}
        placeholder="Amount"
      />
      <input
        value={state.fromToken}
        onChange={(e) => State.update({ fromToken: e.target.value })}
        placeholder="From token"
      />
      <input
        value={state.toToken}
        onChange={(e) => State.update({ toToken: e.target.value })}
        placeholder="To token"
      />
      <button
        onClick={onSwap}
        style={{
          border: 0,
          borderRadius: 10,
          padding: "10px 14px",
          cursor: "pointer",
          background: "#111827",
          color: "white"
        }}
      >
        Swap (wire router action)
      </button>
    </div>
  </div>
);
`
  },
  "portfolio-card": {
    name: "portfolio-card",
    title: "Portfolio Card",
    description: "Portfolio summary card with table layout and PnL placeholders.",
    tags: ["portfolio", "analytics", "dashboard"],
    render: ({ componentName, description }) => `const rows = [
  { symbol: "NEAR", amount: 125.4, usd: 460.22 },
  { symbol: "USDC", amount: 820.0, usd: 820.0 },
  { symbol: "wBTC", amount: 0.03, usd: 1830.5 }
];

const total = rows.reduce((sum, row) => sum + row.usd, 0);

return (
  <div style={{
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    padding: 16,
    maxWidth: 520,
    fontFamily: "Inter, system-ui, sans-serif",
    background: "#fff"
  }}>
    <h3 style={{ marginTop: 0, marginBottom: 8 }}>${componentName}</h3>
    <p style={{ marginTop: 0, color: "#6b7280" }}>${description ?? "Portfolio card scaffold for BOS"}</p>

    <h2 style={{ marginBottom: 12 }}>$ {total.toFixed(2)}</h2>

    <table style={{ width: "100%", borderCollapse: "collapse" }}>
      <thead>
        <tr>
          <th style={{ textAlign: "left", borderBottom: "1px solid #e5e7eb", paddingBottom: 8 }}>Asset</th>
          <th style={{ textAlign: "right", borderBottom: "1px solid #e5e7eb", paddingBottom: 8 }}>Amount</th>
          <th style={{ textAlign: "right", borderBottom: "1px solid #e5e7eb", paddingBottom: 8 }}>USD</th>
        </tr>
      </thead>
      <tbody>
        {rows.map((row) => (
          <tr key={row.symbol}>
            <td style={{ paddingTop: 8 }}>{row.symbol}</td>
            <td style={{ textAlign: "right", paddingTop: 8 }}>{row.amount}</td>
            <td style={{ textAlign: "right", paddingTop: 8 }}>{"$"}{row.usd.toFixed(2)}</td>
          </tr>
        ))}
      </tbody>
    </table>
  </div>
);
`
  }
};

export function listTemplates(): Array<Pick<TemplateDefinition, "name" | "title" | "description" | "tags">> {
  return Object.values(templates).map(({ name, title, description, tags }) => ({
    name,
    title,
    description,
    tags
  }));
}

export function renderTemplate(name: TemplateName, componentName: string, description?: string): string {
  return templates[name].render({ componentName, description });
}

export function isTemplateName(input: string): input is TemplateName {
  return input in templates;
}

export function getTemplate(name: TemplateName): TemplateDefinition {
  return templates[name];
}
